#!/usr/bin/env sh
behat --no-paths features/turnSwitcher.feature
behat --no-paths features/fieldTaker.feature
behat --no-paths features/gameScorer.feature
#behat --no-paths features/tripletChecker.feature

