#!/usr/bin/env sh
#phpunit -c phpunit.xml --testdox --debug --colors --verbose --coverage-text
phpspec lib/PHPPeru/TicTacToe/Spec/ -fd | git commit -a -F -
#behat --no-paths features/turnSwitcher.feature
#behat --no-paths features/fieldTaker.feature
#behat --no-paths features/gameScorer.feature
#behat --no-paths features/tripletChecker.feature

